export const DATA = [
  {
    id: "lkdsjfklj",
    nazev: "kočka",
    cislo_fotky: "17",
    images:['../api/assets/img/0017'],
    typ: ["brož", "spona na oděv"],
    material: ["chirurgická ocel", "drahé kameny"],
    technika: ["kované", "tepané"],
    opracovani: ["leštěné"],
    lokalita: ["české"],
    kamen: ["železitý křemen", "olivín"],
    motiv: ["zoomorfní"],
    kolekce: ["Země česká"],
  },
  {
    id: "skdjfksdf",
    nazev: "blankytně",
    cislo_fotky: "18",
    images:['../api/assets/img/0018'],
    typ: ["náramek"],
    material: ["chirurgická ocel", "drahé kameny"],
    technika_1: ["kované", "tepané"],
    opracovani: ["výbrusy"],
    lokalita_1: ["zahraniční"],
    kamen_1: ["křišťál", "modrý křemen"],
    motiv: ["abstraktní a jiné"],
    kolekce_1: ["Země česká"],
  },
  {
    id: "lkbnjfklj",
    cislo_fotky: "27",
    images:['../api/assets/img/0027'],
    typ: ["náhrdelník"],
    material: ["chirurgická ocel", "drahé kameny"],
    technika: ["kované", "tepané"],
    opracovani: ["leštěné"],
    lokalita: ["zahraniční"],
    kamen: ["achát", "karneol"],
    motiv: ["abstraktní a jiné"],
    kolekce: [""],
    nazev: "divoch",
  },
  {
    id: "lkdsoloo",
    cislo_fotky: "149",
    images:['../api/assets/img/0149'],
    typ: ["souprava"],
    material: ["chirurgická ocel", "drahé kameny"],
    technika: ["kované", "tepané"],
    opracovani: ["leštěné"],
    lokalita: ["zahraniční"],
    kamen: ["australský drahý opál"],
    motiv: ["abstraktní a jiné"],
    kolekce: [""],
    nazev: "opálovost",
  },
  {
    id: "lfvgtklj",
    cislo_fotky: "150",
    images:['../api/assets/img/0150'],
    typ: ["souprava"],
    material: ["chirurgická ocel", "drahé kameny"],
    technika: ["kované", "tepané"],
    opracovani: ["výbrusy"],
    lokalita: ["zahraniční"],
    kamen: ["jaspis", "picasso jaspis"],
    motiv: ["abstraktní a jiné"],
    kolekce: [""],
    nazev: "picasso",
  },
  {
    id: "bnzsjfklj",
    cislo_fotky: "38",
    images:['../api/assets/img/0038'],
    typ: ["brož", "spona na oděv"],
    material: ["chirurgická ocel", "drahé kameny"],
    technika: ["kované", "tepané"],
    opracovani: ["leštěné"],
    lokalita: ["zahraniční"],
    kamen: ["tyrkenit"],
    motiv: ["zoomorfní"],
    kolekce: [""],
    nazev: "tyrkenitový motýl",
  },
  {
    id: "lkdsjmjko",
    cislo_fotky: "48",
    images:['../api/assets/img/0048'],
    typ: ["nahrdelnik"],
    material: ["chirurgická ocel", "fosílie"],
    technika: ["kované", "tepané"],
    opracovani: ["surové"],
    lokalita: ["české", "zahraniční"],
    kamen: ["fosilie", "granát"],
    motiv: ["zoomorfní"],
    kolekce: ["Marokem"],
    nazev: "šnekoid",
  },
  {
    id:"lkdsjmhto",
    cislo_fotky: "30",
    images:['../api/assets/img/0030_a.jpg','../api/assets/img/0030_b.jpg'],
    typ: ["náramek"],
    material: ["chirurgická ocel", "drahé kameny"],
    technika: ["kované", "tepané"],
    opracovani: ["surové"],
    lokalita: ["zahraniční"],
    kamen: ["perla"],
    motiv: ["abstraktní a jiné"],
    kolekce: [""],
    nazev: "perlový náramek",
  },
  {
    id:"amlroawo",
    cislo_fotky: "36",
    images:['../api/assets/img/0036'],
    typ: ["naušnice"],
    material: ["chirurgická ocel", "skleněné"],
    technika: ["kované", "tepané"],
    opracovani: ["leštěné"],
    lokalita: ["zahraniční"],
    kamen: [""],
    motiv: [""],
    kolekce: ["kousek Islandu"],
    nazev: "sea glass",
  },
  {
    id:"bnacgtrto",
    cislo_fotky: "157",
    images:['../api/assets/img/00157_a','../api/assets/img/0157_b'],
    typ: ["přívěšek"],
    material: ["chirurgická ocel", "drahé kameny"],
    technika: ["wire-wrapping"],
    opracovani: ["výbrusy"],
    lokalita: ["zahraniční"],
    kamen: ["rubín"],
    motiv: ["srdce"],
    kolekce: [""],
    nazev: "srdce s asterickým rubínem",
  },
  {
    id:"bxcgrrhto",
    cislo_fotky: "130",
    images:['../api/assets/img/0130'],
    typ: ["naušnice"],
    material: ["měď", "(ne)obyčejné oblázky"],
    technika: ["kované", "tepané"],
    opracovani: ["surové"],
    lokalita: ["zahraniční"],
    kamen: ["surová láva"],
    motiv: ["abstraktní a jiné"],
    kolekce: ["Kousek Islandu"],
    nazev: "bárky z ohně",
  },
  {
    id:"vvloddro",
    cislo_fotky: "363",
    images:['../api/assets/img/0363'],
    typ: ["přívěšek"],
    material: ["zlato", "sdrehé kameny"],
    technika: ["kované", "tepané"],
    opracovani: ["leštěné"],
    lokalita: ["zahraniční"],
    kamen: [""],
    motiv: ["heraldické znamení"],
    kolekce: ["Z dávných dob"],
    nazev: "odřivous",
  },
  {
    id:"yyxnajjto",
    cislo_fotky: "93",
    images:['../api/assets/img/0093','../api/assets/img/0093_a','../api/assets/img/0093_b'],
    typ: ["stříbro"],
    material: ["stříbro", "drahé kameny"],
    technika: ["klenotnická technika"],
    opracovani: ["výbrusy"],
    lokalita: ["zahraniční"],
    kamen: ["kubický zirkon"],
    motiv: ["abstraktní a jiné"],
    kolekce: [""],
    nazev: "vesmír",
  },
  {
    id:"agkuiuhto",
    cislo_fotky: "284",
    images:['../api/assets/img/0284'],
    typ: ["naušnice"],
    material: ["chirurgická ocel", "drahé kameny"],
    technika: ["kované", "tepané"],
    opracovani: ["surové", "leštěné"],
    lokalita: ["české"],
    kamen: ["vltavín, křišťál"],
    motiv: ["abstraktní a jiné"],
    kolekce: ["Země Česká"],
    nazev: "nechranická růže",
  },
  {
    id:"lklijuhto",
    cislo_fotky: "332",
    images:['../api/assets/img/0332'],
    typ: ["přívěšek"],
    material: ["chirurgická ocel", "skleněné"],
    technika: ["kované", "tepané"],
    opracovani: ["surové", "leštěné"],
    lokalita: ["české", "zahraniční"],
    kamen: ["vltavín", "jaspis"],
    motiv: ["křížek"],
    kolekce: ["Země Česká"],
    nazev: "křížek s vltavínem",
  },
  {
    id:"lkdsjmion",
    cislo_fotky: "49",
    images:['../api/assets/img/0049'],
    typ: ["náhrdelník"],
    material: ["chirurgická ocel", "fosílie"],
    technika: ["kované", "tepané"],
    opracovani: ["surové"],
    lokalita: ["zahraniční"],
    kamen: ["fosilie"],
    motiv: ["zoomorfní"],
    kolekce: ["Marokem"],
    nazev: "šnekoid ii",
  },
  {
    id:"lkdsoehto",
    cislo_fotky: "43",
    images:['../api/assets/img/0043'],
    typ: ["přívěšek"],
    material: ["chirurgická ocel", "drahé kameny"],
    technika: ["kované", "tepané"],
    opracovani: ["surové"],
    lokalita: ["zahraniční", "české"],
    kamen: ["křišťál"],
    motiv: ["antropomorfní"],
    kolekce: ["Marokem", "Strážci a andělé"],
    nazev: "křišťálový strážce",
  },
  {
    id:"qltnnbto",
    cislo_fotky: "160",
    images:['../api/assets/img/0160'],
    typ: ["náhrdelník"],
    material: ["chirurgická ocel", "drahé kameny"],
    technika: ["kované", "tepané"],
    opracovani: ["leštěné"],
    lokalita: ["zahraniční"],
    kamen: ["perleť", "křišťál", "granát"],
    motiv: ["zoomorfní"],
    kolekce: ["Okřídlení"],
    nazev: "perleťový motýl",
  },
  {
    id:"lkdsjionb",
    cislo_fotky: "137",
    images:['../api/assets/img/0137'],
    typ: ["brož", "spona na oděv"],
    material: ["chirurgická ocel", "drahé kameny"],
    technika: ["kované", "tepané"],
    opracovani: ["leštěné"],
    lokalita: ["zahraniční", "české"],
    kamen: ["achát"],
    motiv: ["zoomorfní"],
    kolekce: ["Okřídlení"],
    nazev: "brož s ptáčkem",
  },
  {
    id:"ikvaeqgto",
    cislo_fotky: "64",
    images:['../api/assets/img/0064_a','../api/assets/img/0064_b'],
    typ: ["náhrdelník"],
    material: ["chirurgická ocel", "drahé kameny"],
    technika: ["kované", "tepané"],
    opracovani: ["leštěné"],
    lokalita: ["české"],
    kamen: ["achát"],
    motiv: ["antropomorfní"],
    kolekce: ["Stážci a andělé"],
    nazev: "bytost",
  },
];
