
export const TYPE = {
  BROZ: "broz",
  NAHRDELNIK: "nahrdelnik",
  NARAMEK: "naramek",
  NAUSNICE: "nausnice",
  PRIVESEK: "privesek",
  PRSTEN: "prsten",
  SPONA_NA_ODEV: "spona_na_odev",
  SOUPRAVA: "souprava",
  OZDOBA_DO_VLASU: "ozdoba_do_vlasu",
  FIGURKA: "figurka",
};

export const MATERIALS = {
  MOSAZ: "mosaz",
  KERAMIKA: "keramika",
  OBECNY_KOV: "obecny kov",
  DRAHE_KAMENY: "drahe kameny",
  MED: "med",
  SKLENENE: "sklenene",
  ZLATO: "zlato",
  BRONZ: "bronz",
  RECYKLOVANE: "recyklovane",
  STRIBRO: "stribro",
  CHIRURGICKA_OCEL: "chirurgicka ocel",
  OBLAZKY: "(ne)obycejne oblazky",
  PRIRODNINY: "drevo a jine prirodniny",
};

export const LOCATION = {
  CESKE: "ceske",
  ZAHRANICNI: "zahranicni",
};

export const TREATMENT = {
  SUROVE: "surove",
  LESTENE: "lestene",
  VYBRUSY: "vybrusy",
};
export const METHOD = {
  KOVANE: "kovane tepane",
  WIRE_WRAPPING: "wire-wrapping",
  KLENOTNICKA_TECHNIKA: "klenotnicka technika",
};
export const MOTIVE = {
  ZOOMORFNI: "zoomorfni",
  FYTOMORFNI: "fytomorfni",
  ANTROPOMORFNI: "antropomorfni",
  ABSTRAKTNI: "abstraktni a jine",
};
export const COLLECTION = {
  ISLAND: "Kousek Islandu",
  MAROKO: "Marokem",
  OKRIDLENI: "Okridleni",
  ANDELE: "Strazci a andele",
  ZEME_CESKA: "Zeme Ceská",
  DAVNE_DOBY: "Z dávných dob",
};

export const STONE = {
  ACHAT: "achat",
  AKVAMARIN: "akvamarin",
  AMAZONIT: "amazonit",
  AMETYST: "ametyst",
  AMONIT: "amonit",
  APATIT: "apatit",
  ARAUKARIT: "araukarit",
  AUSTRALSKY_DRAHY_OPAL: "australsky_drahy_opal",
  CELESTIN: "celestin",
  CITRIN: "citrin",
  CAROIT: "caroit",
  CERNA_BAROKNI_PERLA: "cerna barokni perla",
  DINOSAURI_KOST: "dinosauri kost",
  DRAHY_OPAL: "drahý opal",
  FLUORIT: "fluorit",
  FOSILIE: "fosilie",
  GRANAT: "granat",
  HEMATIT: "hematit",
  CHALCEDON: "chalcedon",
  CHROMDIOPSID: "chromdiopsid",
  JANTAR: "jantar",
  JASPIS: "jaspis",
  JISKRIVEC: "jiskrivec",
  KALCIT: "kalcit",
  KARNEOL: "karneol",
  KOBALTOKALCIT: "kobaltokalcit",
  KORAL: "koral",
  KREMENNA_HMOTA: "kremenna hmota",
  KRISTAL: "kristal",
  KUBICKY_ZIRKON: "kubicky zirkon",
  KYANIT: "kyanit",
  LABRADORIT: "labradorit",
  LAPIS_LAZULI: "lapis lazuli",
  LARIMAR: "larimar",
  LAVA: "lava",
  LAVOVY_OBLAZEK: "lavový oblazek",
  LYBIJSKE_SKLO: "lybijske sklo",
  MALACHIT: "malachit",
  MESICNI_KAMEN: "mesicni kamen",
  MEXICKY_OHNIVY_OPAL: "mexicky ohnivy opal",
  MODRY_KREMEN: "modry kremen",
  OBSIDIAN: "obsidian",
  OCEANOVY_JASPIS: "oceanový jaspis",
  OHNIVY_OPAL: "ohnivy opal",
  OLIVIN: "olivin",
  OLIVINY: "oliviny",
  OPAL: "opal",
  OPALIZOVANE_DREVO: "opalizovane drevo",
  ORTHOCERAS: "orthoceras",
  PERLA: "perla",
  PERLET: "perlet",
  PICASSO_JASPIS: "picasso jaspis",
  PREHNIT: "prehnit",
  PYRIT: "pyrit",
  RODOCHROZIT: "rodochrozit",
  RODONIT: "rodonit",
  RUBIN: "rubin",
  RUZENIN: "ruzenin",
  SAFIR: "safir",
  SAGENIT: "sagenit",
  SEPTARIE: "septarie",
  SMARAGD: "smaragd",
  SODALIT: "sodalit",
  SOKOLI_OKO: "sokoli oko",
  SPESSARTIN: "spessartin",
  SUGILIT: "sugilit",
  SUROVA_LAVA: "surova lava",
  SVOR: "svor",
  TOPAZ: "topaz",
  TURMALIN: "turmalin",
  TYRKENIT: "tyrkenit",
  TYRKYS: "tyrkys",
  VLTAVIN: "vltavin",
  WAVELIT: "wavelit",
  ZAHNEDA: "zahneda",
  ZELEZITY_KREMEN: "zelezity kremen",
};
