export const PRODUCT_TYPE = {
  BROZ: "brož",
  NAHRDELNIK: "náhrdelník",
  NARAMEK: "náramek",
  NAUSNICE: "náušnice",
  PRIVESEK: "přívěšek",
  PRSTEN: "prsten",
  SPONA_NA_ODEV: "spona na oděv",
  SOUPRAVA: "souprava",
  OZDOBA_DO_VLASU: "ozdoba do vlasů",
  FIGURKA: "figurka",
};

export const MATERIALS = {
  MOSAZ: "mosaz",
  KERAMIKA: "keramika",
  OBECNY_KOV: "obecný kov",
  DRAHE_KAMENY: "drahé kameny",
  MED: "měď",
  SKLENENE: "skleněné",
  ZLATO: "zlato",
  BRONZ: "bronz",
  RECYKLOVANE: "recyklované",
  STRIBRO: "stříbro",
  CHIRURGICKA_OCEL: "chirurgická ocel",
  OBLAZKY: "(ne)obyčejné oblázky",
  PRIRODNINY: "dřevo a jiné přírodniny",
};

export const LOCATION = {
  CESKE: "české",
  ZAHRANICNI: "zahraniční",
};

export const TREATMENT = {
  SUROVE: "surové",
  LESTENE: "leštěné",
  VYBRUSY: "výbrusy",
};
export const METHOD = {
  KOVANE: "kované tepané",
  WIRE_WRAPPING: "wire-wrapping",
  KLENOTNICKA_TECHNIKA: "klenotnická technika",
};
export const MOTIVE = {
  ZOOMORFNI: "zoomorfní",
  FYTOMORFNI: "fytomorfní",
  ANTROPOMORFNI: "antropomorfní",
  ABSTRAKTNI: "abstraktní a jiné",
};
export const COLLECTION = {
  ISLAND: "kousek Islandu",
  MAROKO: "Marokem",
  OKRIDLENI: "Okřídlení",
  ANDELE: "Strážci a andělé",
  ZEME_CESKA: "Země Česká",
  DAVNE_DOBY: "Z dávných dob",
};

export const STONE = {
  ACHAT: "achát",
  AKVAMARIN: "akvamarín",
  AMAZONIT: "amazonit",
  AMETYST: "ametyst",
  AMONIT: "amonit",
  APATIT: "apatit",
  ARAUKARIT: "araukarit",
  AUSTRALSKY_DRAHY_OPAL: "australský drahý opál",
  CELESTIN: "celestin",
  CITRIN: "citrín",
  CAROIT: "čaroit",
  CERNA_BAROKNI_PERLA: "černá barokní perla",
  DINOSAURI_KOST: "dinosauří kost",
  DRAHY_OPAL: "drahý opál",
  FLUORIT: "fluorit",
  FOSILIE: "fosilie",
  GRANAT: "granát",
  HEMATIT: "hematit",
  CHALCEDON: "chalcedon",
  CHROMDIOPSID: "chromdiopsid",
  JANTAR: "jantar",
  JASPIS: "jaspis",
  JISKRIVEC: "jiskřivec",
  KALCIT: "kalcit",
  KARNEOL: "karneol",
  KOBALTOKALCIT: "kobaltokalcit",
  KORAL: "korál",
  KREMENNA_HMOTA: "křemenná hmota",
  KRISTAL: "křišťál",
  KUBICKY_ZIRKON: "kubický zirkon",
  KYANIT: "kyanit",
  LABRADORIT: "labradorit",
  LAPIS_LAZULI: "lapis lazuli",
  LARIMAR: "larimar",
  LAVA: "láva",
  LAVOVY_OBLAZEK: "lávový oblázek",
  LYBIJSKE_SKLO: "lybijské sklo",
  MALACHIT: "malachit",
  MESICNI_KAMEN: "měsíční kámen",
  MEXICKY_OHNIVY_OPAL: "mexický ohnivý opál",
  MODRY_KREMEN: "modrý křemen",
  OBSIDIAN: "obsidián",
  OCEANOVY_JASPIS: "oceánový jaspis",
  OHNIVY_OPAL: "ohnivý opál",
  OLIVIN: "olivín",
  OLIVINY: "olivíny",
  OPAL: "opál",
  OPALIZOVANE_DREVO: "opalizované dřevo",
  ORTHOCERAS: "orthoceras",
  PERLA: "perla",
  PERLET: "perleť",
  PICASSO_JASPIS: "picasso jaspis",
  PREHNIT: "prehnit",
  PYRIT: "pyrit",
  RODOCHROZIT: "rodochrozit",
  RODONIT: "rodonit",
  RUBIN: "rubín",
  RUZENIN: "růženín",
  SAFIR: "safír",
  SAGENIT: "sagenit",
  SEPTARIE: "septárie",
  SMARAGD: "smaragd",
  SODALIT: "sodalit",
  SOKOLI_OKO: "sokolí oko",
  SPESSARTIN: "spessartin",
  SUGILIT: "sugilit",
  SUROVA_LAVA: "surová láva",
  SVOR: "svor",
  TOPAZ: "topaz",
  TURMALIN: "turmalín",
  TYRKENIT: "tyrkenit",
  TYRKYS: "tyrkys",
  VLTAVIN: "vltavín",
  WAVELIT: "wavelit",
  ZAHNEDA: "záhněda",
  ZELEZITY_KREMEN: "železitý křemen",
};
