
export const TYPE = {
  BROZ: "broz",
  NAHRDELNIK: "nahrdelnik",
  NARAMEK: "naramek",
  NAUSNICE: "nausnice",
  PRIVESEK: "privesek",
  PRSTEN: "prsten",
  SPONA_NA_ODEV: "spona_na_odev",
  SOUPRAVA: "souprava",
  OZDOBA_DO_VLASU: "ozdoba_do_vlasu",
  FIGURKA: "figurka",
};

export const MATERIALS = {
  MOSAZ: "mosaz",
  KERAMIKA: "keramika",
  OBECNY_KOV: "obecny kov",
  DRAHE_KAMENY: "drahe kameny",
  MED: "med",
  SKLENENE: "sklenene",
  ZLATO: "zlato",
  BRONZ: "bronz",
  RECYKLOVANE: "recyklovane",
  STRIBRO: "stribro",
  CHIRURGICKA_OCEL: "chirurgicka ocel",
  OBLAZKY: "(ne)obycejne oblazky",
  PRIRODNINY: "drevo a jine prirodniny",
};

export const LOCATION = {
  CESKE: "ceske",
  ZAHRANICNI: "zahranicni",
};

export const TREATMENT = {
  SUROVE: "surove",
  LESTENE: "lestene",
  VYBRUSY: "vybrusy",
};
export const METHOD = {
  KOVANE: "kovane tepane",
  WIRE_WRAPPING: "wire-wrapping",
  KLENOTNICKA_TECHNIKA: "klenotnicka technika",
};
export const MOTIVE = {
  ZOOMORFNI: "zoomorfni",
  FYTOMORFNI: "fytomorfni",
  ANTROPOMORFNI: "antropomorfni",
  ABSTRAKTNI: "abstraktni a jine",
};
export const COLLECTION = {
  ISLAND: "Kousek Islandu",
  MAROKO: "Marokem",
  OKRIDLENI: "Okridleni",
  ANDELE: "Strazci a andele",
  ZEME_CESKA: "Zeme Ceská",
  DAVNE_DOBY: "Z dávných dob",
};

export const STONE = {
  ACHAT: "achát",
  AKVAMARIN: "akvamarín",
  AMAZONIT: "amazonit",
  AMETYST: "ametyst",
  AMONIT: "amonit",
  APATIT: "apatit",
  ARAUKARIT: "araukarit",
  AUSTRALSKY_DRAHY_OPAL: "australský drahý opál",
  CELESTIN: "celestin",
  CITRIN: "citrín",
  CAROIT: "čaroit",
  CERNA_BAROKNI_PERLA: "černá barokní perla",
  DINOSAURI_KOST: "dinosauří kost",
  DRAHY_OPAL: "drahý opál",
  FLUORIT: "fluorit",
  FOSILIE: "fosilie",
  GRANAT: "granát",
  HEMATIT: "hematit",
  CHALCEDON: "chalcedon",
  CHROMDIOPSID: "chromdiopsid",
  JANTAR: "jantar",
  JASPIS: "jaspis",
  JISKRIVEC: "jiskřivec",
  KALCIT: "kalcit",
  KARNEOL: "karneol",
  KOBALTOKALCIT: "kobaltokalcit",
  KORAL: "korál",
  KREMENNA_HMOTA: "křemenná hmota",
  KRISTAL: "křišťál",
  KUBICKY_ZIRKON: "kubický zirkon",
  KYANIT: "kyanit",
  LABRADORIT: "labradorit",
  LAPIS_LAZULI: "lapis lazuli",
  LARIMAR: "larimar",
  LAVA: "láva",
  LAVOVY_OBLAZEK: "lávový oblázek",
  LYBIJSKE_SKLO: "lybijské sklo",
  MALACHIT: "malachit",
  MESICNI_KAMEN: "měsíční kámen",
  MEXICKY_OHNIVY_OPAL: "mexický ohnivý opál",
  MODRY_KREMEN: "modrý křemen",
  OBSIDIAN: "obsidián",
  OCEANOVY_JASPIS: "oceánový jaspis",
  OHNIVY_OPAL: "ohnivý opál",
  OLIVIN: "olivín",
  OLIVINY: "olivíny",
  OPAL: "opál",
  OPALIZOVANE_DREVO: "opalizované dřevo",
  ORTHOCERAS: "orthoceras",
  PERLA: "perla",
  PERLET: "perleť",
  PICASSO_JASPIS: "picasso jaspis",
  PREHNIT: "prehnit",
  PYRIT: "pyrit",
  RODOCHROZIT: "rodochrozit",
  RODONIT: "rodonit",
  RUBIN: "rubín",
  RUZENIN: "růženín",
  SAFIR: "safír",
  SAGENIT: "sagenit",
  SEPTARIE: "septárie",
  SMARAGD: "smaragd",
  SODALIT: "sodalit",
  SOKOLI_OKO: "sokolí oko",
  SPESSARTIN: "spessartin",
  SUGILIT: "sugilit",
  SUROVA_LAVA: "surová láva",
  SVOR: "svor",
  TOPAZ: "topaz",
  TURMALIN: "turmalín",
  TYRKENIT: "tyrkenit",
  TYRKYS: "tyrkys",
  VLTAVIN: "vltavín",
  WAVELIT: "wavelit",
  ZAHNEDA: "záhněda",
  ZELEZITY_KREMEN: "železitý křemen",
};
